### ISSUE TITLE
Is there a discord server or something similar?

### ISSUE THREAD

**Issue by Blackgarion** [furka/40k-10th-list-builder#2]
Hello I came to the repo from a comment made on the sub reddit of WH40k, I think in order to develop the feature of reading the data set from battlescribe requires a bit more coordination and could be worked in chunks instead of sending a huge pull request, I was wondering is there any discord server or way to communicate with you?

**Comment by furka** [comment]
I will look into setting one up

**Comment by furka** [comment]
Discord server: https://discord.gg/CtbC5kBeJ2
